plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/setups/hunter_se/hunter_se_plugin_config.yaml'

pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'
  sem_.*: 'exponential'
  # semantic_rgb: 'color'

#### Publishers ########
# topic_name:
#   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
#   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
#   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance', 'rgb', 'color_rgb']
    basic_layers: ['elevation', 'traversability']
    fps: 5.0

  # filtered_elevation_map:
  #   layers: ['inpaint', 'smooth', 'min_filter', 'erosion']
  #   basic_layers: ['inpaint']
  #   fps: 5.0

  semantic_map_raw:
    layers: ['elevation', 'traversability', 'variance', 'rgb', 'semantic_rgb', 'color_rgb',
            'friction', 'stiffness', 
            'inpaint', 'scientific_value', 'geometry_traversability']
    basic_layers: ['inpaint']
    fps: 5.0

#### Subscribers ########
subscribers:
  front_nav_depth:
    topic_name: /zed2i/zed_node/point_cloud/cloud_registered
    data_type: pointcloud

  # back_obstacle_depth:
  #   topic_name: /ZED/camera_obs_b/depth/point_cloud
  #   data_type: pointcloud

  front_nav_rgb:
    topic_name: /zed2i/zed_node/rgb/image_rect_color/compressed
    camera_info_topic_name: /zed2i/zed_node/rgb/camera_info
    data_type: image
    channel_info_topic_name: /zed2i/zed_node/rgb/channel_info

  # front_nav_semantic:
  #   topic_name: /ZED/camera_nav/semantic/semantic_viz
  #   camera_info_topic_name: /ZED/camera_nav/semantic/camera_info  # TODO: use the throttled one
  #   data_type: image
  #   channel_info_topic_name: /ZED/camera_nav/semantic/viz_channel_info

  # front_nav_friction:
  #   topic_name: /ZED/camera_nav/friction/friction_image
  #   camera_info_topic_name: /ZED/camera_nav/semantic/camera_info
  #   data_type: image
  #   channel_info_topic_name: /ZED/camera_nav/friction/channel_info
  
  # front_nav_stiffness:
  #   topic_name: /ZED/camera_nav/stiffness/stiffness_image
  #   camera_info_topic_name: /ZED/camera_nav/semantic/camera_info  # TODO: use the throttled one
  #   data_type: image
  #   channel_info_topic_name: /ZED/camera_nav/stiffness/channel_info

  # front_nav_scientific_value:
  #   # here I get the semantic probability and tranform to scientific value through plugin, so that the previous information in map can be updated as well
  #   topic_name: /ZED/camera_nav/science/semantic_prob  # 0 - no rock; >0 - has rock with value
  #   camera_info_topic_name: /ZED/camera_nav/rgb/camera_info  # TODO: use the throttled one
  #   data_type: image
  #   channel_info_topic_name: /ZED/camera_nav/science/channel_info

  velodyne:
    topic_name: /velodyne_points
    data_type: pointcloud