# Settings of the plugins. (The plugins should be stored in script/plugins)

# # min_filter fills in minimum value around the invalid cell.
# min_filter:                                   
#   enable: True                                # weather to load this plugin
#   fill_nan: False                             # Fill nans to invalid cells of elevation layer.
#   is_height_layer: True                       # If this is a height layer (such as elevation) or not (such as traversability)
#   layer_name: "min_filter"                    # The layer name.
#   extra_params:                               # This params are passed to the plugin class on initialization.
#     dilation_size: 1                          # The patch size to apply
#     iteration_n: 30                           # The number of iterations

# # Apply smoothing.
# smooth_filter:                                
#   enable: True
#   fill_nan: False
#   is_height_layer: True
#   layer_name: "smooth"
#   extra_params:
#     input_layer_name: "min_filter"

# Apply inpainting using opencv
inpainting:
  enable: True
  fill_nan: False
  is_height_layer: True
  layer_name: "inpaint"
  extra_params:
    method: "telea"                           # telea or ns

# Apply semantic rgb filter
semantic_color_filter:
  enable: False
  fill_nan: False
  is_height_layer: False
  layer_name: "semantic_rgb"
  extra_params:
    channels: ['semantic_r', 'semantic_g', 'semantic_b']

# Apply scientific value filter
scientific_filter:
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "scientific_value"
  extra_params:
    classes: ['_background_', 'normal_rock', 'scientific_rock']

# Apply physical traversability
physical_traversability:
  enable: False
  fill_nan: False
  is_height_layer: False
  layer_name: "physical_traversability"
  extra_params:
    friction_layer_name: "friction"
    stiffness_layer_name: "stiffness"
    friction_threshold: 0.5
    stiffness_threshold: 0.5

geometry_traversability:
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "geometry_traversability"
  extra_params:
    input_layer_name: "inpaint"
    height_threshold: 0.2

traversability_filter:
  enable: False
  fill_nan: false
  is_height_layer: false
  layer_name: "binary_traversability"
  extra_params:
    input_layer_name: "traversability"
    traversability_threshold: 0.1
